import React from 'react'
import './_mobileTerms.scss';
const MobileTerms = () => {
  return (
    <div className="main-wrapper">
			<div className="intro-inner">
				<div className="shell-top">
					<div className="intro__content">
						<h2 className='title'>Mobile App Terms of Use</h2>
					</div>
				</div>
			</div>

			<article className="article">
				<div className="shell">
					<div className="article__head">
						{/* <h2>Mobile App Terms of Use</h2> */}

						<h3>Bluon, Inc.(“Bluon”, “we”, “our”, or “us”)</h3>
					</div>

					<div className="article__body">
						<p>Bluon users, we have your back! Bluon has been built from the ground up to serve, empower, and inform HVAC technicians and professionals. As we continue to grow, we become a bigger target. The following binding Terms of Use and Privacy Policy are here to protect us so that we can continue to serve and protect you in the Bluon way. Thanks for being a Bluon user!</p>
						
						<h3>1. Terms</h3>
						<p>These Mobile App Terms of Use (these “Terms”) describe your rights and responsibilities when accessing and using the Bluon mobile application and any and all related materials, information, software and services offered by Bluon in connection therewith (collectively, the “Mobile App”). By accessing or using the Mobile App, you (a) acknowledge that you have read and understand these Terms; (b) represent that you are 18 years of age or older; (c) represent that you are an HVAC/R technician, contractor, supplier, student, or other professional in the HVAC industry; and (d) agree to be bound by and comply with these Terms, the Privacy Policy, and all applicable laws and regulations. If you do not agree with these Terms, you are prohibited from using or accessing the Mobile App.</p>
						<p>PLEASE READ THESE TERMS CAREFULLY TO ENSURE THAT YOU UNDERSTAND EACH PROVISION. THESE TERMS CONTAIN A MANDATORY INDIVIDUAL ARBITRATION AND A CLASS ACTION/JURY TRIAL WAIVER PROVISION THAT REQUIRES THE USE OF ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES, RATHER THAN JURY TRIALS OR CLASS ACTIONS.</p>
						
						<h3>2. Changes to the Terms</h3>
						<p>Bluon may revise these Terms at any time. By using the Mobile App, you agree to be bound by the then current version of these Terms. If we make material changes to the Terms or Privacy Policy, we will notify you based upon the communication channel that you select. You are responsible for ensuring that we have an up-to-date, active, and deliverable email address and phone number for you and for periodically visiting our Terms and Privacy Policy to check for updates.</p>
					
						<h3>3. User License</h3>
						<p>Subject to these Terms, Bluon grants you a limited, non-exclusive, nontransferable license to download, install, and use the Mobile App on one or more mobile device(s) owned or otherwise controlled by you strictly in accordance with the Bluon’s documentation. These Terms permit you to use the Mobile App for your own personal, non-commercial use and purposes. All copyright contained on the Mobile App is either owned by Bluon or its licensors, or published solely for educational and instructional purposes, except for certain User Contributions discussed herein. This use license is at no charge to you. You recognize and agree that your ability to use and reuse the information contained on the Mobile App is limited by these Terms. You must not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, scrap, or transmit any of the material on our Mobile App, except that your phone or computer may temporarily store copies of such materials in RAM incidental to your accessing and viewing those materials and you may store files that are automatically cached by the Mobile App for display enhancement purposes. This is a grant of a license, not a transfer of title, and under this license you must not:</p>
						<ul>
							<li>Modify or copy any materials from the Mobile App;</li>
							<li>Use any illustrations, photographs, video or audio sequences, or any graphics separately from the accompanying text;</li>
							<li>Delete or alter any copyright, trademark, or other proprietary rights notices from copies of materials from the Mobile App;</li>
							<li>Access or use for any commercial purposes any part of the Mobile App or any services or materials available through the Mobile App;</li>
							<li>Attempt to decompile or reverse engineer any software, copyright, or other information contained on the Mobile App, or otherwise attempt to derive or gain access to the source code of the Mobile App or any part thereof;</li>
							<li>Scrap any data; or,</li>
							<li>Transfer the materials to another person or “mirror” the materials on any other server.</li>
						</ul>
						<p>This license shall automatically terminate if you violate any of these restrictions, and Bluon may terminate your use license at any time. Upon terminating your license, you must destroy any downloaded materials in your possession whether in electronic or printed format. If you print, copy, modify, download, or otherwise use or provide any other person with access to any part of the Mobile App in breach of the Terms, your license and right to use the Mobile App will stop immediately and you must cease using the Mobile App and return or destroy any copies of the materials you have made. Any use of the Mobile App not expressly permitted by these Terms is a breach of these Terms and may violate copyright, trademark, and other laws. All rights not expressly granted are reserved by Bluon.</p>
					
						<h3>4. Accessing the Mobile App and Account Security; Communications</h3>
						<p>We reserve the right to withdraw or amend the Mobile App and any service or material we provide on the Mobile App in our sole discretion without notice. We will not be liable if for any reason all or any part of the Mobile App is unavailable at any time or for any period. From time to time, we may restrict access to some parts of the Mobile App, or the entire Mobile App, to users, including registered users. You are responsible for both making all arrangements necessary for you to have access to the Mobile App and ensuring that all persons who access the Mobile App through your mobile device are aware of these Terms and comply with them.</p>
						<p>To access the Mobile App or the resources it offers, you may be asked to provide certain registration details or other information, including providing personal identifying information such as your name, phone number, email address, physical address, location data, and other information. To utilize the Mobile App as intended, you must agree to receive telephone calls, text messages, and/or emails from Bluon. It is a condition of your use of the Mobile App that all the information you provide on the Mobile App is correct, current, and complete. You agree that all information you provide to register with the Mobile App or otherwise, including, but not limited to, through the use of any interactive features on the Mobile App, is governed by our Privacy Policy and you consent to all actions we take with respect to your information consistent with our Privacy Policy.</p>
						<p>If you choose a username, password, or any other piece of information as part of our security procedures, you must treat such information as confidential, and you must not disclose it to any other person or entity. You also acknowledge that your account is personal to you and agree not to provide any other person with access to the Mobile App or portions of it using your username, password, or other security information. You agree to notify us immediately of any unauthorized access to or use of your username or password or any other breach of security. You should use particular caution when accessing your account from a shared phone so that others are not able to view or record your password or other personal information. We have the right to disable any account, username, password, or other identifier, whether chosen by you or provided by us, at any time in our sole discretion for any or no reason.</p>
						<p><strong>By creating an account, or by otherwise providing your email address or your mobile phone number, you consent to the Bluon Communications Policy set forth at the end of these Terms.</strong></p>
					
						<h3>5. Bluon Rewards Program</h3>
						<p>By creating an account and using the Mobile App, you may have access to Bluon’s rewards and loyalty program, as described in more detail below and on the Mobile App (the “Rewards Program”). </p>
						<p><strong>Eligibility; Enrollment.</strong> The Rewards Program is open to legal residents of the 50 United States of America and Washington D.C. who are 18 years of age or older.  The Rewards Program and any Points (as defined in the section titled “Earning Points” below) you earn are intended for your personal, non-commercial use only. To use the Rewards Program and earn Points (as further described in the paragraph below), you must first download the Mobile App, agree to these Terms, and create an account. Your use of the Mobile App constitutes your continued agreement to these Terms and the rules and restrictions for the Rewards Program described herein (as they may be updated from time to time), and representation that you meet the eligibility requirements for the Rewards Program described herein.</p>
						<p><strong>Earning Points.</strong> Subject to the rights and restrictions set forth herein, including without limitation Bluon’s right to remove and/or deduct Points as further described in the section titled “Removal and Expiration of Points” below and elsewhere in these Terms, you may accumulate loyalty points (“Points”) on your account based on your Approved Quotes (as defined below) or by engaging in other approved Rewards Program activities that Bluon may make available from time to time, in each case as described below or in the Mobile App. As used herein, an “Approved Quote” is a quote for specific goods that (a) you have received from an authorized distributor on the Bluon platform in response to a valid order request from your account for such goods; and (b) you (or a representative from your company) have (i) confirmed by marking such quote as “Approved” via the live link provided through the Mobile App, and (ii) arranged for pickup from or delivery by the applicable distributor. </p>
						<ul>
							<li key="1">Points From Approved Quotes. If you are eligible to receive Points for Approved Quotes, your account will receive Points at a default rate of 0.50% (the “Default Rate”) of the dollar amount of the Approved Quote, rounded to the nearest whole dollar, excluding tax, shipping charges, fees, and any applied discounts. For example purposes only, an Approved Quote for $1,000 that is eligible for Points at the Default Rate will result in 500 Points credited to your account (0.50% of $1,000 = 500). Notwithstanding anything to the contrary herein or in the Mobile App, Bluon has the right to limit or change the Default Rate at any time in its sole discretion.</li>
							<li key="2">Points From Other Rewards Program Activities. Bluon may also from time to time and in its sole discretion offer opportunities to earn Points for engaging in certain activities to all or some users of the Mobile App (which may or may not include you). Such opportunities (and the details and terms thereof, including how to participate and other limitations or restrictions) may be communicated to you through the Mobile App or through other communication methods that you have authorized.  </li>
						</ul>
						<p><strong>Redeeming Points.</strong> Points may be exchanged for certain Rewards Program-exclusive account benefits and certain merchandise, experiences, or other items as may be identified by Bluon on the Mobile App from time to time (“Rewards”). Rewards may be provided by Bluon or, subject to Section 10 of these Terms, a third party. You are responsible for the payment of all taxes which may result from participation in the Rewards Program. You can check your Points balance in the applicable section of the Mobile App. Rewards are subject to exclusions and special terms.</p>
						<p><strong>Removal and Expiration of Points.</strong> Without limiting Bluon’s other rights set forth herein, including without limitation the rights described in the sections titled “Bluon’s Right to Suspend or Terminate Participation” and “Bluon’s Right to Suspend, Cancel or Change Rewards Program Terms” below, Bluon may, in its sole and absolute discretion, remove and/or deduct earned Points (a) in the event the applicable Approved Quote, or your order, is cancelled or otherwise terminated (whether by you, the distributor, or otherwise) or (b) after 12 months of Rewards Program inactivity (purchase or Point redemption). </p>
						<p><strong>No Cash Value or Transferability.</strong> Points do not constitute property, do not entitle you to a vested right or interest, and do not have any cash value. As such, Points are not redeemable for cash and are not transferable or assignable for any reason. The sale or transfer of Points is strictly prohibited and any such sale or transfer shall be deemed void.  </p>
						<p><strong>Bluon’s Right to Suspend or Terminate Participation.</strong> Bluon reserves the right to deduct Points and suspend and/or terminate your participation in the Rewards Program without notice to you and in its sole discretion, including if Bluon determines that you have violated these Terms or that the use of your account or the Mobile App is unauthorized, deceptive, fraudulent, unlawful, or intentionally subverts the purposes of the Rewards Program’s rules and restrictions. In the event that Bluon cancels the Rewards Program or your participation in the Rewards Program is otherwise terminated, all Points in your account are void and will be forfeited without compensation.</p>
						<p><strong>Bluon’s Right to Suspend, Cancel or Change Rewards Program Terms.</strong> Bluon reserves the right to modify, amend, suspend or terminate any aspect of the Rewards Program at any time and for any reason at its sole discretion. </p>
						
					
						<h3>6. Intellectual Property Rights</h3>
						<p>The Mobile App and its entire contents, features, and functionality (including but not limited to all information, software, text, displays, images, video, and audio, and the design, selection, and arrangement thereof) are owned by Bluon, its licensors, or other providers of such material and are protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws. The Bluon name, these Terms, and company logo and all related names, logos, product and service names, designs, and slogans are trademarks of Bluon or its affiliates or licensors. You must not use such marks without the prior written permission of Bluon. All other names, logos, product and service names, designs, and slogans on the Mobile App is the trademarks of their respective owners. If you believe that any material or User Contributions violate your copyright, please see our Copyright Policy for instructions on sending us a notice of copyright infringement. It is the policy of Bluon to terminate the user accounts of repeat infringers.</p>
						<h3>7. Prohibited Uses</h3>
						<p>You may use the Mobile App only for lawful purposes in accordance with these Terms, except you agree not to use the Mobile App:</p>
						<ul>
							<li>In any way that violates any applicable federal, state, local, or international law or regulation (including, without limitation, any laws regarding the export of data or software to and from the US or other countries);</li>
							<li>For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content, asking for personally identifiable information, or otherwise;</li>
							<li>To send, knowingly receive, upload, download, use, or reuse any material that does not comply with the Content Standards set out in these Terms;</li>
							<li>To transmit, or procure the sending of, any advertising or promotional material without our prior written consent, including any "junk mail," "chain letter," "spam," or any other similar solicitation;</li>
							<li>To impersonate or attempt to impersonate Bluon, a Bluon employee, another user, or any other person or entity (including, without limitation, by using email addresses associated with any of the foregoing);</li>
							<li>To engage in any other conduct that restricts or inhibits anyone's use or enjoyment of the Mobile App, or which, as determined by us, may harm Bluon or users of the Mobile App, or expose them to liability;</li>
							<li>In any manner that could disable, overburden, damage, or impair the Mobile App or interfere with any other party's use of the Mobile App, including their ability to engage in real time activities through the Mobile App;</li>
							<li>By engaging any robot, spider, or other automatic device, process, or means to access the Mobile App for any purpose, including monitoring or copying any of the material on the Mobile App;</li>
							<li>For any manual process to monitor or copy any of the material on the Mobile App, or for any other purpose not expressly authorized in these Terms, without our prior written consent;</li>
							<li>To interfere with the proper working of the Mobile App;</li>
							<li>To introduce any viruses, Trojan horses, worms, logic bombs, or other material that is malicious or technologically harmful;</li>
							<li>To attempt to gain unauthorized access to, damage, or disrupt any parts of the Mobile App, the server on which the Mobile App is stored, or any server, computer, or database connected to the Mobile App; or,</li>
							<li>Attack or attempt to interfere with the Mobile App.</li>
						</ul>

						<h3>8. Monitoring and Enforcement; Termination</h3>
						<p>We have the right to:</p>
						<ul>
							<li>Remove or refuse to post any User Contributions for any or no reason in our sole</li>
							<li>Take any action with respect to any User Contribution that we deem necessary or appropriate in our sole discretion, including if we believe that such User Contribution violates the Terms, including the Content Standards, infringes any intellectual property right or other right of any person or entity, threatens the personal safety of users of the Mobile App or the public, could create liability for Bluon, or as Bluon determines in its sole and absolute discretion;</li>
							<li>Disclose your identity or other information about you to any third party who claims that material posted by you violates their rights, including their intellectual property rights or their right to privacy;</li>
							<li>Take appropriate legal action, including without limitation, referral to law enforcement, for any illegal or unauthorized use of the Mobile App; and,</li>
							<li>Terminate or suspend your access to all or part of the Mobile App for any or no reason, including without limitation, any violation of these Terms or the Privacy Policy.</li>
						</ul>
						<p>Without limiting the foregoing, we have the right to cooperate fully with any law enforcement authorities or court order requesting or directing us to disclose the identity or other information of anyone posting any materials on or through the Mobile App. YOU WAIVE AND HOLD HARMLESS THE COMPANY FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY THE COMPANY DURING, OR TAKEN AS A CONSEQUENCE OF, INVESTIGATIONS BY EITHER THE COMPANY OR LAW ENFORCEMENT AUTHORITIES.</p>
						<p>We do not undertake to review all material before it is posted on the Mobile App and cannot ensure prompt removal of objectionable material after it has been posted. Accordingly, we assume no liability for any action or inaction regarding any User Contributions, including any transmissions, communications, or content provided by any user or third party; however, we do reserve the unilateral right to remove any objectionable material or reasonably modify any material for publication. We have no liability or responsibility to anyone for performance or nonperformance of the activities described in this section.</p>

						<h3>9. User Contributions; Content Standards</h3>
						<p>The Mobile App may allow you to submit, post, display, provide, or otherwise make available content such as images, comments, questions, and other content or information (“User Contributions”).</p>
						<p>WE CLAIM NO OWNERSHIP RIGHTS OVER YOUR USER CONTRIBUTIONS, AND, AS BETWEEN YOU AND BLUON, IT REMAINS YOURS. Bluon has the right (but not the obligation), in its sole discretion, to remove any User Contributions shared via the Mobile App.</p>
						<p>By submitting, posting, displaying, providing, or otherwise making available any User Contributions on or through the Mobile App, you hereby expressly grant, and you represent and warrant that you have all rights necessary to grant, to Bluon a royalty-free, transferable, perpetual, irrevocable, non-exclusive, and worldwide license, with the right to grant and authorize sublicenses, to use, reproduce, modify, publish, list information regarding, edit, translate, distribute, syndicate, publicly perform, publicly display, and make derivative works of all such User Contributions and your name, voice, and/or likeness as contained in your User Contributions, in whole or in part, and in any form, media, or technology, whether now known or hereafter developed, for use in connection with the Mobile App and Bluon’s (and its successors’) business, including, without limitation, for promoting and redistributing part or all of the Mobile App (and derivative works thereof) in any media formats and through any media channels.</p>
						<p>These content standards apply to any and all User Contributions. User Contributions must entirety comply with all applicable federal, state, local, and international laws and regulations. Without limiting the foregoing, User Contributions must not:</p>
						<ul>
							<li>Contain any material that is defamatory, obscene, indecent, abusive, offensive, harassing, violent, hateful, inflammatory, or otherwise objectionable;</li>
							<li>Promote sexually explicit or pornographic material, violence, or discrimination based on race, sex, religion, nationality, disability, sexual orientation, or age;</li>
							<li>Infringe any patent, trademark, trade secret, copyright, or other intellectual property or other rights of any other person;</li>
							<li>Violate the legal rights (including the rights of publicity and privacy) of others or contain any material that could give rise to any civil or criminal liability under applicable laws or regulations or that otherwise may be in conflict with these Terms, Copyright Policy, or Privacy Policy;</li>
							<li>Be likely to deceive any person;</li>
							<li>Promote any illegal activity, or advocate, promote, or assist any unlawful act;</li>
							<li>Cause annoyance, inconvenience, or needless anxiety or is likely to upset, embarrass, alarm, or annoy any other person, as determined at Bluon’s sole and absolute discretion;</li>
							<li>Impersonate any person or misrepresent your identity or affiliation with any person or organization;</li>
							<li>Involve commercial activities or sales, such as contests, sweepstakes, and other sales promotions, barter, or advertising; or</li>
							<li>Give the impression that they emanate from or are endorsed by us or any other person or entity, if this is not the case.</li>
						</ul>
						<p>In connection with your User Contributions, you affirm, represent, and warrant the following:</p>
						<ul>
							<li>You have the written consent of each and every identifiable natural person referred to or mentioned in the User Contributions, if any, to use such person’s name or likeness in the manner contemplated by the Mobile App and these Terms, and each such person has released you from any liability that may arise in relation to such use;</li>
							<li>you have obtained and are solely responsible for obtaining all consents as may be required by applicable law to post any User Contributions relating to third parties;</li>
							<li>your User Contributions and Bluon’s use thereof as contemplated by these Terms and the Mobile App will not violate any applicable law or infringe any rights of any third party, including, but not limited to, any intellectual property rights and privacy rights;</li>
							<li>Bluon may exercise the rights to your User Contributions granted under these Terms without liability for payment of any guild fees, residuals, payments, fees, or royalties payable under any collective bargaining agreement or otherwise; </li>
							<li>your User Contributions do not include nudity or other sexually suggestive content; hate speech, threats, or direct attacks on an individual or group; abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, invasive of another’s privacy, hateful, or racially, ethnically, or otherwise objectionable content; content that contains self-harm or excessive violence; illegal content or content in furtherance of harmful or illegal activities; malicious programs or code; any person’s personal information without such person’s consent; and/or spam, machine-generated content, or unsolicited messages; and</li>
							<li>to the best of your knowledge, all of your User Contributions and all other information that you provide to us are truthful and accurate</li>
						</ul>

						<h3>10.	Third-Party Services and Materials. </h3>
						<p>The Mobile App may contain links to third-party materials and services that are not owned or controlled by Bluon. Further, to use the Mobile App, you may be required to register for third-party services and/or to otherwise enable various third-party services that may directly integrate with the Mobile App (collectively, “Third-Party Services”). Bluon does not endorse or assume any responsibility for any third-party sites, nor for any information, materials, products, or services (including, without limitation, Third-Party Services) available on or through third-party sites. If you access a third-party website or service (including, without limitation, a Third-Party Service) from the Mobile App or share your User Contributions on or through any third-party website or service (including, without limitation, a Third-Party Service), you do so at your own risk, and you understand that these Terms and our Privacy Policy do not apply to your access to or use of such sites or services. You acknowledge that a Third-Party Service may revoke your right to access and/or authenticate to such Third-Party Service at any time. As such, Bluon is not liable for any damage or loss caused or alleged to be caused by or in connection with your use of or reliance on any Third-Party Service. Bluon enables Third-Party Services merely as a convenience to its users, and the inclusion of Third-Party Services does not imply an endorsement or recommendation of them. You expressly relieve Bluon from any and all liability arising from your access to and/or use of any third-party website, service, or content, including, without limitation, User Contributions submitted by other users. Additionally, your dealings with or participation in promotions of advertisers found on the Mobile App, including payment and delivery of goods, and any other terms (such as warranties) are solely between you and such advertisers. You agree that Bluon will not be responsible for any loss or damage of any sort relating to your dealings with such advertisers.</p>

						<h3>11. Disclaimer</h3>
						<p>THE MOBILE APP IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. USE OF THE MOBILE APP IS AT YOUR OWN RISK. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, BLUON MAKES NO WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, AND HEREBY SPECIFICALLY DISCLAIMS ALL WARRANTIES, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT OF INTELLECTUAL PROPERTY, OR VIOLATION OF ANY OTHER RIGHT, AND ALL WARRANTIES ARISING FROM COURSE OF DEALING, USAGE, OR TRADE PRACTICE. BLUON MAKES NO WARRANTY OF ANY KIND THAT THE MOBILE APP OR ANY PRODUCTS OR RESULTS OF THE USE THEREOF WILL MEET YOUR OR ANY OTHER PERSON’S REQUIREMENTS, OPERATE WITHOUT INTERRUPTION, ACHIEVE ANY INTENDED RESULT, BE COMPATIBLE OR WORK WITH ANY SOFTWARE, SYSTEM OR OTHER PLATFORM, OR BE SECURE, ACCURATE, COMPLETE, FREE OF HARMFUL CODE, OR ERROR FREE. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, BLUON MAKES ABSOLUTELY NO WARRANTY OR REPRESENTATION REGARDING THE TECH SUPPORT, QUOTING TOOLS, RETROFIT INSTRUCTIONS, OR ANY OTHER SERVICES, INFORMATION, OR MATERIALS OFFERED VIA THE MOBILE APP. YOU UNDERSTAND AND AGREE THAT BY ACCESSING AND USING THE MOBILE APP YOU REPRESENT AND WARRANT THAT YOU ARE EXPERIENCED IN THE TRADE OF HVAC AND THAT YOU ARE FULLY RESPONSIBLE FOR ALL WORK PERFORMED. BLUON MAKES ABSOLUTELY NO REPRESENTATION OR WARRANTY CONCERNING THE ACCURACY, LIKELY RESULTS, OR RELIABILITY OF THE USE OF ANY SERVICES, INFORMATION, OR MATERIALS ON ITS MOBILE APP, INCLUDING WITHOUT LIMITATION THE RETROFIT INSTRUCTIONS, THE OEM USER MANUALS, OR OTHERWISE, AND ALL SUCH INFORMATION AND MATERIALS ARE PROVIDED “AS IS” “WHERE IS” AND WITHOUT ANY WARRANTY WHATSOEVER.</p>

						<h3>12. Limitations on Liability</h3>
						<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL BLUON, ANY OEM, ANY DISTRIBUTOR, OR ANY RELATED THIRD PARTY, OR ANY EMPLOYEES, CONTRACTORS, AGENTS, OFFICERS, OR DIRECTORS OF THE FOREGOING, BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF DATA, PROFITS, GOODWILL, WARRANTY VIOLATION, BUSINESS INTERRUPTION OR OTHERWISE) ARISING OUT OF OR RELATING TO THE USE OF - OR INABILITY TO USE - THE MOBILE APP. UNDER NO CIRCUMSTANCES WILL BLUON BE RESPONSIBLE FOR ANY DAMAGE, LOSS, OR INJURY RESULTING FROM HACKING, TAMPERING, OR OTHER UNAUTHORIZED ACCESS TO OR USE OF THE MOBILE APP OR YOUR USER ACCOUNT OR THE INFORMATION CONTAINED THEREIN.</p>
						<p>THIS LIMITATIONS ON LIABILITY SECTION APPLIES WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER BASIS, EVEN IF BLUON HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.</p>
						<p>THE MAXIMUM AGGREGATE LIABILITY FOR BLUON SHALL BE LIMITED TO THE AMOUNT ANY USER PAYS BLUON. BECAUSE SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES, OR LIMITATIONS OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THESE LIMITATIONS MAY NOT APPLY TO YOU.</p>

						<h3>13. Revisions and errata</h3>
						<p>The materials appearing on the Mobile App could include technical, typographical, or photographic errors. Bluon does not warrant that any of the materials on its Mobile App is accurate, complete, or current. Bluon may make changes to the materials contained on its Mobile App at any time without notice; however, Bluon does not make any commitment to update the materials.</p>

						<h3>14. Indemnification</h3>
						<p>You agree to defend, indemnify, and hold harmless Bluon, its affiliates, OEMs, licensors, and service providers, and its and their respective officers, directors, employees, contractors, attorneys, agents, licensors, suppliers, successors, and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to your violation of these Terms, your use of the Mobile App, or any third party claims for services rendered by you, including, but not limited to, your User Contributions, your use of Tech Support, your use of TdX 20 Retrofit, your use of quoting tools,  or any other use of the Mobile App's content, services, and products or your use of any information obtained from the Mobile App.</p>
					
						<h3>15. Governing Law and Jurisdiction</h3>

						<p>These Terms and any claim relating to Bluon’s Mobile App shall be governed by the laws of Delaware without regard to its conflict of law provisions.  Notwithstanding the preceding sentence with respect to the substantive law governing these Terms, the Federal Arbitration Act (9 U.S.C. §§ 1-16) (“FAA”) governs the interpretation and enforcement of the arbitration terms set forth in Section 16 below (the “Arbitration Agreement”) and preempts all state laws (and laws of other jurisdictions) to the fullest extent permitted by applicable law. If the FAA is found to not apply to any issue that arises from or relates to the Arbitration Agreement, then that issue will be resolved under and governed by the law of the U.S. state where you live (if applicable) or the jurisdiction mutually agreed upon in writing by you and us. The application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded. You agree to submit to the exclusive personal jurisdiction of the federal and state courts located in Delaware for any actions for which we retain the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation, or violation of our intellectual property rights or other proprietary rights, as set forth in the Arbitration Agreement below, including any provisional relief required to prevent irreparable harm. You agree that Delaware is the proper and exclusive forum for any appeals of an arbitration award or for trial court proceedings in the event that the Arbitration Agreement below is found to be unenforceable.</p>

						<h3>16. Binding Arbitration and Class Action/Jury Trial Waiver</h3>
						<p>We hope we never have a dispute, but if we do, you agree to try for 60 days to resolve it informally by contacting us at terms@bluon.com. If we cannot find a resolution, you agree to binding individual arbitration before the American Arbitration Association (“AAA”) under the Federal Arbitration Act (“FAA”), and not to sue in court in front of a judge or jury. Instead, a neutral arbitrator will decide, and the arbitrator’s decision will be final except for a limited right to appeal under the FAA. Class action lawsuits, class-wide arbitrations, private attorney-general actions, and any other proceedings where someone acts in a representative capacity are not allowed. Nor is combining individual proceedings without the consent of all parties. Judgment on the award rendered by the arbitrator(s) may be entered in any court having jurisdiction thereof. The parties understand and agree that this provision limits their ability to seek any form of judicial relief or other remedy outside of those mentioned herein.</p>
						<p>Claims shall be heard by a single arbitrator, unless the claim amount exceeds $75,000, in which case the dispute shall be heard by a panel of three arbitrators. The arbitration shall be governed by the laws of the State of Delaware. The arbitrators will have no authority to award damages outside of these Terms, except as may be required by statute. The arbitrator(s) shall not award incidental, consequential, or punitive damages in any arbitration initiated under this section. The award of the arbitrators shall be accompanied by a reasoned opinion. Except as may be required by law, neither a party nor an arbitrator may disclose the existence, content, or results of any arbitration hereunder without the prior written consent of both parties.</p>
						<p>Nothing in this Arbitration Agreement will be deemed as preventing Bluon from seeking injunctive or other equitable relief from the courts as necessary to prevent the actual or threatened infringement, misappropriation, or violation of its data security, intellectual property rights, or other proprietary rights; or preventing you from asserting claims in small claims court, provided that your claims qualify, and so long as the matter remains in such court and advances on only an individual (non-class, non-representative) basis.</p>
						<p>If you are a new user of the Mobile App, you can reject and opt-out of this Arbitration Agreement within thirty (30) days of accepting these Terms by emailing Bluon at terms@bluon.com with your full, legal name and stating your intent to opt-out of this Arbitration Agreement. Note that opting out of this Arbitration Agreement does not affect any other part of these Terms, including the provisions regarding controlling law or the courts in which any disputes must be brought.</p>
						<p>REGARDLESS OF THE TYPE OF USER YOU ARE, INCLUDING WHETHER YOU ARE A NATURAL PERSON OR AN ENTITY, ANY CLAIM MUST BE BROUGHT IN YOUR INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION, COLLECTIVE ACTION, PRIVATE ATTORNEY GENERAL ACTION, OR OTHER REPRESENTATIVE PROCEEDING. THIS CLASS ACTION/JURY TRIAL WAIVER APPLIES TO CLASS ARBITRATION, AND, UNLESS WE AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON’S CLAIMS. YOU AND BLUON AGREE THAT THE ARBITRATOR MAY AWARD RELIEF ONLY TO AN INDIVIDUAL CLAIMANT AND ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF ON YOUR INDIVIDUAL CLAIM(S). ANY RELIEF AWARDED MAY NOT AFFECT OTHER USERS. YOU AND BLUON FURTHER AGREE THAT, BY ENTERING INTO THESE TERMS, YOU AND BLUON ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO BRING, JOIN, OR PARTICIPATE IN A CLASS ACTION, COLLECTIVE ACTION, PRIVATE ATTORNEY GENERAL ACTION, OR OTHER REPRESENTATIVE PROCEEDING OF ANY KIND AS A PLAINTIFF OR CLASS MEMBER.</p>

						<h3>17. Waiver and Severability</h3>
						<p>No waiver by Bluon of any term or condition set out in these Terms shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure to assert a right or provision under these Terms shall not constitute a waiver of such right or provision. If any provision of these Terms is held by a court, arbitrator, or other tribunal of competent jurisdiction to be invalid, illegal, or unenforceable for any reason, such provision shall be eliminated or limited. Notwithstanding, the remaining provisions of the Terms will continue in full force and effect.</p>

						<h3>18. Links</h3>
						<p>Bluon has not reviewed all of the site or pages linked to its Mobile App and is not responsible for the contents of any such linked site or page. The inclusion of any link does not imply endorsement by Bluon of the Mobile App, and the use of any such linked site or page is at YOUR OWN RISK.</p>

						<h3>19. Entire Agreement</h3>
						<p>These Terms and our Privacy, Communication, and DMCA Policies constitute the sole and entire agreement between you and Bluon regarding the Mobile App and supersede all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral.</p>
						
						<h2>Communications Policy</h2>
						{/* <div style='color:red'>  */}
							<h3>Bluon Alerts Short Code Program</h3>
							<h5>Program Description </h5>
							<p>Bluon offers its text messaging program whereby Bluon will text message you to provide you with updates on application features/functionality (all the foregoing the “Bluon Alerts”). Bluon may, from time to time, deliver text messages to you under the Bluon Alerts.</p>
							<h5>Opt-out </h5>
							<p>You can opt-out at any time by texting “STOP” or by contacting Bluon at (855) 4258686 or terms@bluon.com.</p>
							<h5>Help</h5>
							<p>If you are experiencing issues with the messaging program you can reply with the keyword “HELP” for more assistance, or you can get help directly at (855) 4258686 or terms@bluon.com.</p>
							<h5>Fees</h5>
							<p>Message and data rates apply for any messages sent to you from us and to us from you. Carriers are not liable for delayed or undelivered messages. Frequency of messaging varies.</p>
							<p>If you have any questions about your text plan or data plan, it is best to contact your wireless provider.</p>
							<h5>Privacy Policy </h5>
							<p>If you have any questions regarding privacy, please read our privacy policy below.</p>

						{/* </div>  */}
						
						<h3>Bluon, Inc.</h3>
						<p><strong>General.</strong> When signing up for the Mobile App you choose your preferred contact method and authorize Bluon to contact you via email, text, and/or call. If you have any questions regarding privacy, please read our Privacy Policy.</p>
						<p><strong>Text Messaging.</strong> By signing up for the Mobile App and providing your mobile phone number, you expressly consent and agree that Bluon may contact you using written, electronic, or verbal means, including by manual dialing, emails, leaving prerecorded/artificial voice messages or using an automatic telephone dialing system to call or text your mobile/cellular telephone number, as necessary to complete transactions requested by you and to service your account and as the law allows, even if those phone numbers are registered by you on any federal or state Do-Not-Call/Do-Not-email registry. </p>
						<p>We may send text messages to (a) provide you with information and updates on quote requests, Mobile App features, account-related news and alerts, and/or marketing and promotional offers for Bluon products and services; (b) help keep your account secure through the use of two-factor authentication; (c) help you access your account; and/or (d) as otherwise necessary to service your account and/or to enforce these Terms, our policies, applicable law, and/or any other agreement we may have with you. By signing up for an account and providing us your mobile phone number, you certify that such number is true and accurate and that you are authorized to enroll the designated number to receive text messages. You acknowledge and agree that the text messages may be sent using an automatic telephone dialing system. </p>
						<p>Neither Bluon, nor any carrier, is liable or otherwise responsible for any delays upon sending or receiving text messages, or for any undelivered text messages.  As always, message and data rates may apply for any text messages sent to you from us and to us from you. Message frequency varies. If you have any questions about your text plan or data plan, it is best to contact your wireless provider.</p>
						<p>To unsubscribe from text messages at any time, reply “STOP” to any text message you receive from Bluon, or contact Bluon at <a href="tel:(855) 425-8686">(855) 425-8686</a> or <a href='mailto:terms@bluon.com'>terms@bluon.com</a>.  You consent that following such a request to unsubscribe, you may receive one final text message from Bluon confirming your request. After this, you will no longer receive text messages from us. If you want to join again, just sign up as you did the first time and we will start sending text messages to you again.</p>
						<p>If you are experiencing issues with our text messaging program you can reply with the keyword “HELP” for more assistance, or you can get help directly at <a href="contactus@bluon.com">contactus@bluon.com</a> or <a href="(855) 425-8686">(855) 425-8686</a></p>
						<p><strong>Email</strong>. By providing us your email address, you consent to our using that email address to send you notices relating to the Mobile App and other Bluon services, and to send you any notices required by applicable law in lieu of communication by postal mail. We may also use your email address to send you other messages, such as messages notifying you of changes to features of the Mobile App or other Bluon services, and special offers. If you do not want to receive such email messages, you may opt out of receiving such email messages by clicking on the “unsubscribe” link in the email message received and/or change your preferences in your settings page. Opting out may prevent you from receiving email messages regarding updates, improvements, or offers.</p>
						<p><strong>Phone Calls</strong>. By signing up for the Mobile App and providing your mobile phone number, you consent to receive autodialed or prerecorded calls from us at the telephone number(s) provided by you to us. We may place such calls to (a) help keep your account secure through the use of two-factor authentication; (b) help you access your account when you’ve forgotten your password; or (c) as otherwise necessary to service your account or enforce these Terms, our policies, applicable law, or any other agreement we may have with you.</p>

						<h2>Copyright Policy</h2>
						<h3>DIGITAL MILLENNIUM COPYRIGHT ACT (“DMCA”) NOTICE</h3>
						<p>This notice is for informational purposes only. It is not intended as, nor should it be construed as, legal advice. If you believe that your intellectual property rights have been infringed upon, or if a notice of infringement has been filed against you, you should immediately seek legal counsel. This App, including all text, HTML, scripts, and images are copyrighted – or used under the Fair Use Doctrine - and owned by Bluon, Inc. All rights reserved. No part of this App may be reproduced or transmitted in any form or by any means, mechanical, electronic, or otherwise, including photocopying and recording, or by any information storage and retrieval system, or transmitted by email, or used in any other fashion without the express prior written permission of Bluon. This, of course, excludes the downloading and temporary caching of this App on your mobile phone for the explicit purpose of viewing, as well as any information clearly marked as reproducible. This copyright notice applies to everyone, including all users of the Mobile App.</p>
						<h3>DMCA PROVISIONS</h3>
						<p>The Digital Millennium Copyright Act of 1998, found at 17 U.S.C. § 512 (“DMCA”), provides recourse for owners of copyrighted materials who believe that their rights under United States copyright law have been infringed upon on the Internet. Under the DMCA, the bona fide owner of copyrighted materials who has a good faith belief that their copyright has been infringed may contact Bluon, the person or entity, or the designated agent of the ISP to report alleged infringements of their protected works, when such alleged infringements appear on pages contained within the App.</p>
						<p>Bluon is committed to complying with international trade law, international trade practices, all United States laws, including United States copyright law. Upon receipt of a properly filed complaint under the DMCA, Bluon will block access to the allegedly infringing material and will forward a copy of the notification of claimed copyright infringement to the alleged infringer. Anyone who believes in good faith that a notice of copyright infringement has wrongfully been filed against them may submit a Counternotice to Bluon.</p>
						<h3>NOTIFICATION OF CLAIMED COPYRIGHT INFRINGEMENT</h3>
						<p>Please send DMCA notifications of claimed copyright infringement to Bluon, Inc. at 18 Bunsen, Irvine, CA 92618 U.S.A. To file a notice of infringement with Bluon, you must provide written communication that sets forth the items specified below. You will be liable for damages (including damages, costs, and attorneys’ fees) if you materially misrepresent that the App or a page is infringing your copyright. Accordingly, if you are not sure whether certain material of yours is protected by copyright laws, we suggest that you first contact an attorney. To expedite our ability to process your request, please use the following format (including section numbers):</p>
						<ol>
							<li key="1">Identify in sufficient detail the copyrighted work that you believe has been infringed upon;</li>
							<li key="2">Identify the material that you claim is infringing the copyrighted work listed in item #1 above. You must include the location(s) of the page(s) that contains the allegedly infringing material and also include a description of the specific content which you claim is infringing on your copyright;</li>
							<li key="3">Provide information reasonably sufficient to permit Bluon to contact you (name, email address, and a phone number are required, at minimum);</li>
							<li key="4">Include the following statement: “I swear, under penalty of perjury, that the information in the notification is accurate and that I am the copyright owner or am authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. I also affirm that as the copyright owner, I have a good faith belief that use of the material in the manner complained of is not authorized by me, my agent, or the law”; and,</li>
							<li key="5">The signature of the copyright owner or a person authorized to act on behalf of the copyright owner.</li>
						</ol>

						<p>You may send your notice via email provided such notice includes a proper electronic signature.</p>
						<p>For details on the information required for valid notification, see 17 U.S.C. § 512(c)(3).</p>

						<h3>COUNTERNOTIFICATION TO CLAIMED COPYRIGHT INFRINGEMENT</h3>
						<p>If a notice of copyright infringement has been filed against you, Bluon will attempt to notify you and provide you with a copy of the notice of copyright infringement. If you have a good faith belief that you have been wrongfully accused, you may file a counternotification with Bluon. If Bluon receives a valid counter notification, the DMCA provides that the removed or blocked information will be restored or access reenabled. Bluon will replace the removed material and cease disabling access to it in not less than 10, nor more than 14, business days following receipt of the counternotification, unless Bluon first receives notice from the complaining party that such complaining party has filed an action seeking a court order to restrain the alleged infringer from engaging in infringing activity relating to the material on this website. Please be advised that United States copyright law provides substantial penalties for a false counternotice filed in response to a notice of copyright infringement. Accordingly, if you are not sure whether certain material of yours is protected by copyright laws, we suggest that you first contact an attorney.</p>

						{/* <div class="red-section" style="color:red"> */}
							<h2>Privacy Policy</h2>
							<h3>Bluon, Inc.</h3>
							<h3>1. Introduction</h3>
							<p>Bluon developed this Privacy Policy to show you how we collect, use, communicate, disclose, and make use of your personal information. We are committed to ensuring the confidentiality of personal information. Bluon may change this Privacy Policy from time to time, at its sole discretion. The following outlines our privacy policy:</p>
							<ul>
								<li>You provide us certain personal identifying information at the time you download the App, including but not limited to your name, email, phone number, and postal code, which should be and remain accurate, complete, and up to date;</li>
								<li>You grant us permission to use this information to grow the business relationship, including to provide you services, updates, marketing materials, and otherwise communicate;</li>
								<li>You are free to opt-out at any time by following the instructions provided;</li>
								<li>We will collect and use personal information pursuant to these Terms and for the purposes described herein; and,</li>
								<li>We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.</li>
								<p>This policy applies to information we collect:</p>
								<li>On our Mobile App;</li>
								<li>In email, text, and other electronic messages between you and the Mobile App; and,</li>
								<li>When you interact with our advertising, tech support, and applications on third-party websites and services.</li>
								<p>It does not apply to information collected by:</p>
								<li>Us offline or through any other means, including on any other Mobile App or website operated by us or any third party; or</li>
								<li>Any third party, including through any application or content (including advertising) that may link to or be accessible from or on our Mobile App.</li>
							</ul>
						{/* </div> */}
							<p>Please read this policy carefully to understand our policies and practices regarding your information and how we will treat it. If you do not agree with our policies and practices, your choice is not to use our Mobile App. By accessing or using the Mobile App, you agree to this Privacy Policy. This policy may change from time to time at Bluon’s sole discretion. Your continued use of the Mobile App after we make changes is deemed to be acceptance of those changes, so please check the policy periodically for updates. By using the App, you accept that Bluon may collect data according to this Privacy Policy.</p>
							<h3>2. Children Under the Age of 16</h3>
							<p>Our Mobile App is not intended for children under 16 years of age. No one under age 16 may provide any information to or on the Mobile App. We do not knowingly collect personal information from children under 16. If you are under 16, do not use or provide any information on this Mobile App. If we learn we have collected or received personal information from a child under 16 without verification of parental consent, we will delete that information. If you believe we might have any information from or about a child under 16, please contact us at terms@bluon.com. California residents under 16 years of age may have additional rights regarding the collection and sale of their personal information. Please see [Your California Privacy Rights] for more information.</p>
							<h3>3. Information We Collect About You and How We Collect It</h3>
							<p>We collect several types of information from and about users of our Mobile App, including information:</p>
							<ul>
								<li>By which you may be personally identified, such as name, postal address, e-mail address, telephone number, or any other identifier by which you may be contacted online or offline (“personal information”);</li>
								<li>That is about you but individually does not identify you; and,</li>
								<li>About your internet connection, the equipment you use to access our Mobile App, and usage</li>
								<p>We collect this information:</p>
								<li>Directly from you when you provide it to us;</li>
								<li>Automatically as you navigate through the site, such as usage details, IP addresses, and information collected through cookies.</li>
							</ul>
							<h3>Information You Provide to Us</h3>
							<p>The information we collect on or through our Mobile App may include:</p>
							<ul>
								<li>Information that you provide by filling in forms on our Mobile App. This includes information provided at the time of registering to use our Mobile App, subscribing to our service, posting material, or requesting further services. We may also ask you for information if you report a problem with our Mobile App.</li>
								<li>Records and copies of your correspondence (including email addresses and phone calls), if you contact</li>
								<li>Your responses to surveys that we might ask you to complete for research</li>
								<li>Details of transactions you carry out through our Mobile App.</li>
								<li>Your search queries on the Mobile App.</li>
							
							</ul>
							<p>You also may provide information to be published or displayed (hereinafter, "posted") on public areas of the Mobile App or transmitted to other users of the Mobile App or third parties (collectively, "User Contributions"). Your User Contributions are posted on and transmitted to others at your own risk. Please be advised that no security measure is perfect or impenetrable. Additionally, we cannot control the actions of other users of the Mobile App with whom you may choose to share your User Contributions. Therefore, we cannot and do not guarantee that your User Contributions will not be viewed by unauthorized persons.</p>
							<h3>Information We Collect Through Automatic Data Collection Technologies</h3>
							<p>As you navigate through and interact with our Mobile App, we may use automatic data collection technologies to collect certain information about your equipment, browsing actions, and patterns, including:</p>
							<ul>
								<li>Details of your visits to our Mobile App, including traffic data, location data, logs, and other communication data and the resources that you access and use on the Mobile App; and,</li>
								<li>Information about your computer and internet connection, including your IP address, operating system, and browser</li>
								<p>We also may use these technologies to collect information about your online activities over time and across third-party mobile apps or other online services (behavioral tracking).
									The information we collect automatically may include personal information, or we may maintain it or associate it with personal information we collect in other ways or receive from third parties. It helps us to improve our Mobile App and to deliver a better and more personalized service, including by enabling us to:</p>
								<li>Estimate our audience size and usage</li>
								<li>Store information about your preferences, allowing us to customize our Mobile App according to your individual</li>
								<li>Speed up your searches.</li>
								<li>Recognize you when you return to our Mobile App.</li>
								<p>We may use technologies to automatically collect data including, but not limited to:</p>
								<li>Cookies (or browser cookies). A cookie is a small file placed on the hard drive of your computer. You may refuse to accept browser cookies by activating the appropriate setting on your browser. However, if you select this setting, you may be unable to access certain parts of our Mobile App. Unless you have adjusted your browser setting so that it will refuse cookies, our system will issue cookies when you direct your browser to our Mobile App.</li>
								<li>Flash Cookies. Certain features of our Mobile App may use local stored objects (or Flash cookies) to collect and store information about your preferences and navigation to, from, and on our Mobile App. Flash cookies are not managed by the same browser settings as are used for browser cookies.</li>
								<li>Web Beacons. Pages of our Mobile App may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, tracking pixels, advertising pixels, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or and for other related Mobile App statistics (for example, recording the popularity of certain Mobile App content and verifying system and server integrity).</li>
							</ul>
							<h3>4. Third-Party Use of Cookies and Other Tracking Technologies</h3>
							<p>Some content or applications, including advertisements, on the Mobile App is served by third parties, including advertisers, ad networks and servers, content providers, and application providers. These third parties may use cookies to collect information about you when you use our Mobile App. The information they collect may be associated with your personal information or they may collect information, including personal information, about your online activities over time and across different mobile apps and other online services. They may use this information to provide you with interest-based (behavioral) advertising or other targeted content. We do not control these third parties' tracking technologies or how they may be used. If you have any questions about an advertisement or other targeted content, you should contact the responsible provider directly.</p>
					
							<h3>5. How We Use Your Information</h3>
							<p>We use information that we collect about you or that you provide to us, including any personal information:</p>
							<ul>
								<li>To present our Mobile App and its contents to</li>
								<li>To provide you with information, products, or services that you request from</li>
								<li>To fulfill any other purpose for which you provide</li>
								<li>To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection.</li>
								<li>To notify you about changes to our Mobile App or any products or services we offer or provide though</li>
								<li>To allow you to participate in interactive features on our Mobile App.</li>
								<li>In any other way we may describe when you provide the</li>
								<li>For any other purpose with your consent, which includes your prior express written consent</li>
							</ul>
							<p>We may use the information we have collected from you to enable us to display advertisements to our advertisers' target audiences. Even though we do not disclose your personal information for these purposes without your consent, if you place an order, click on, or otherwise interact with an advertisement, the advertiser may assume that you meet its target criteria.</p>

							<h3>6. Disclosure of Your Information</h3>
							<p>We may disclose aggregated information about our users and information that does not identify any individual, without restriction. We may disclose personal information that we collect, or you provide as described in this Privacy Policy:</p>
							<ul>
								<li>To our subsidiaries and affiliates;</li>
								<li>To contractors, service providers, and other third parties we use to support our business and use it only for the purposes for which we disclose it to them;</li>
								<li>To a buyer or other successor in the event of a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Bluon’s assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which personal information held by Bluon about our Mobile App users is among the assets transferred;</li>
								<li>To third parties to market their products or services to you if you have not opted out of these disclosures;</li>
								<li>Data obtained through the short code program will not be shared with any third-parties for their marketing reasons/purposes;</li>
								<li>To fulfill the purpose for which you provide it;</li>
								<li>For any other purpose disclosed by us when you provide the information; and</li>
								<li>With your consent.</li>
							</ul>
							<p>We may also disclose your personal information:</p>
							<ul>
								<li>To comply with any court order, law, or legal process, including to respond to any government or regulatory request;</li>
								<li>To enforce or apply our Terms and other agreements, including for billing and collection purposes; and,</li>
								<li>If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of Bluon, our customers, or others. This includes exchanging information with other companies and organizations for the purposes of fraud protection and credit risk</li>
							</ul>
							<h3>7. Choices About How We Use and Disclose Your Information</h3>
							<p>We strive to provide you with choices regarding the personal information you provide to us. We have created mechanisms to provide you with the following control over your information:</p>
							<ul>
								<li><strong>Tracking Technologies and Advertising.</strong> You can set your browser to refuse all or some browser cookies, or to alert you when cookies are being sent. To learn how you can manage your Flash cookie settings, visit the Flash player settings page on Adobe's Mobile AppWebsite. If you disable or refuse cookies, please note that some parts of the Mobile App may then be inaccessible or not function</li>
								<li><strong>Promotional Offers from the Company.</strong> If you do not wish to have your information used by the Company to promote our own or third parties' products or services, you can opt-out via the email feature or by sending an email stating your request to <a href='mailto:terms@bluon.com'>terms@bluon.com</a>. If we have sent you a promotional email, you may send us a return email asking to be omitted from future email distributions.</li>
								<li><strong>Targeted Advertising.</strong> If you do not want us to use information that we collect or that you provide to us to deliver advertisements according to our advertisers' target-audience preferences, you can opt-out by sending us an email stating your request to <a href='mailto:terms@bluon.com'>terms@bluon.com</a>.</li>
							</ul>
							<p>We do not control third parties' collection or use of your information to serve interest-based advertising. However, these third parties may provide you with ways to choose not to have your information collected or used in this way. You can opt out of receiving targeted ads from members of the Network Advertising Initiative ("<strong>NAI</strong>") on the NAI's Mobile App Website. California residents may have additional personal information rights and choices. Please see [Your California Privacy Rights] for more information.</p>
							
							<h3>8. Accessing and Correcting Your Information</h3>
							<p>You can review and change your personal information by logging into the Mobile App and visiting your account profile page. You may also send us an email at terms@bluon.com to request access to, correct, or delete any personal information that you have provided to us. We cannot delete your personal information except by also deleting your user account. We may not accommodate a request to change information if we believe the change would violate any law or legal requirement or cause the information to be incorrect. If you delete your User Contributions from the Mobile App, copies of your User Contributions may remain viewable in cached and archived pages or might have been copied or stored by other Mobile App users.</p>
							<h3>9. Your California Privacy Rights</h3>
							<p>If you are a California resident, California law may provide you with additional rights regarding our use of your personal information. California's "Shine the Light" law (Civil Code Section § 1798.83) permits users of our app that are California residents to request certain information regarding our disclosure of personal information to third parties for their direct marketing purposes. To make such a request, please send an email to terms@bluon.com.</p>
							<h3>10. Data Security</h3>
							<p>We have implemented reasonable measures designed to secure your personal information from accidental loss and from unauthorized access, use, alteration, and disclosure. All information you provide to us is stored on our secure servers behind firewalls. Unfortunately, the transmission of information via the internet is not completely secure. Although we do our best to protect your personal information, we cannot guarantee the security of your personal information transmitted to our Mobile App. Any transmission of personal information is at your own risk. We are not responsible for circumvention of any privacy settings or security measures contained on the Mobile App.</p>
							<p>The safety and security of your information also depends on you. Where we have given you (or where you have chosen) a password for access to certain parts of our Mobile App, you are responsible for keeping this password confidential. We ask you not to share your password with anyone. We urge you to be careful about giving out information in public areas of the Mobile App like message boards. The information you share in public areas may be viewed by any user of the Mobile App.</p>
							<h3>11. Changes to Our Privacy Policy</h3>
							<p>It is our policy to notify you if any material changes to how we treat our users’ personal information via the preferred contact method that you select. The date the Privacy Policy was last revised is identified at the top of the page. You are responsible for ensuring we have an up-to-date active and deliverable email address for you, and for periodically visiting our Mobile App and this Privacy Policy to check for any changes.</p>
						</div>
				</div>
			</article>
		</div>
  )
}

export default MobileTerms